name: "[Workflow] Path To Live - Add LPA To Pod Service"

on:
  push:
    branches:
      - main
    paths:
      - 'service-add-lpa-to-pod/**'
      - '.github/workflows/**'

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Jest Tests
    uses: ./.github/workflows/test_job.yml

  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: [
      create_tags,
      test
    ]
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
    secrets: inherit

  terraform_account_workflow:
    name: TF Apply Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: development
      working_directory: ./service-add-lpa-to-pod/terraform/account
    secrets: inherit

  production_deploy:
    name: Production Deploy
    needs: [
      create_tags,
      terraform_account_workflow,
      docker_build_scan_push
      ]
    uses: ./.github/workflows/terraform_environment_job.yml
    with:
      workspace_name: production
      version_tag: ${{ needs.create_tags.outputs.version_tag }}
      working_directory: ./service-add-lpa-to-pod/terraform/environment
    secrets: inherit


  end_of_main_workflow:
    name: End of Main Workflow
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: "https://${{ needs.production_deploy.outputs.url }}"
    needs: [
      docker_build_scan_push,
      terraform_account_workflow,
      production_deploy
    ]
    steps:
      - name: End of Path to Live Workflow
        run: |
          echo "production environment tested, built and deployed"
