on:
  workflow_call:
    inputs:
      workspace_name:
        description: 'The terraform workspace to target for account actions'
        required: true
        type: string
      working_directory:
        description: 'The working directory for account level terraform configuration'
        required: true
        type: string
jobs:
  terraform_account_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: unfor19/install-aws-cli-action@v1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.6
      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-duration-seconds: 3600
          role-session-name: OPGModernisingLPATerraformGithubAction

      - name: Lint Terraform
        working-directory: ${{ inputs.working_directory }}
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ${{ inputs.working_directory }}
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
        run: |
          terraform workspace show
          terraform plan -input=false -parallelism=30

      - name: Terraform Apply
        working-directory: ${{ inputs.working_directory }}
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30
