name: "[Workflow] Path To Live - Revoke Service"

on:
  push:
    branches:
      - main
    paths:
      - 'service-revoke/**'

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  production_deploy:
      name: PR Environment Deploy
      uses: ./.github/workflows/terraform_environment_job.yml
      with:
        workspace_name: production
        working_directory: ./service-revoke/terraform/environment
      secrets: inherit

  end_of_production_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    # environment:
    #   name: ${{ needs.create_tags.outputs.environment_workspace_name }}
    #   url: "https://${{ needs.pr_deploy.outputs.url }}"
    needs: [
      production_deploy,
      ]
    steps:
      - name: End of Production Workflow
        run: |
          echo "workflow complete!"

