name: "[Workflow] PR - Add LPA To Pod Service"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'service-add-lpa-to-pod/**'
      - '.github/workflows/**'

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  # test:
  #   name: Jest Tests
  #   uses: ./.github/workflows/test_job.yml

  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  docker_build_scan_push:
    name: Docker Build, Scan and Push
    uses: ./.github/workflows/docker_job.yml
    needs: [
      create_tags,
      # test
      ]
    with:
      tag: ${{ needs.create_tags.outputs.version_tag }}
    secrets: inherit

  # terraform_account_workflow:
  #   name: TF Plan Dev Account
  #   uses: ./.github/workflows/terraform_account_job.yml
  #   with:
  #     workspace_name: development
  #     working_directory: ./service-add-lpa-to-pod/terraform/account
  #   secrets: inherit

  pr_deploy:
      name: PR Environment Deploy
      needs: [
        create_tags,
        docker_build_scan_push
        ]
      uses: ./.github/workflows/terraform_environment_job.yml
      with:
        workspace_name: ${{ needs.create_tags.outputs.environment_workspace_name }}
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
        working_directory: ./service-add-lpa-to-pod/terraform/environment
      secrets: inherit

  end_of_pr_workflow:
    name: End of PR Workflow
    runs-on: ubuntu-latest
    # environment:
    #   name: "dev_${{ needs.create_tags.outputs.environment_workspace_name }}"
    #   url: "https://${{ needs.pr_deploy.outputs.url }}"
    needs: [
      # docker_build_scan_push,
      pr_deploy,
      # create_tags,
      # terraform_account_workflow
      ]

    steps:
      - name: End of PR Workflow
        run: |
          echo "workflow complete!"
          # echo "${{ needs.pr_deploy.outputs.terraform_workspace_name }} PR environment tested, built and deployed"
          # echo "Tag Deployed: ${{ needs.pr_deploy.outputs.terraform_container_version }}"
          # echo "URL: https://${{ needs.pr_deploy.outputs.url }}"
